name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: cd src && go test
      - run: go run src/math.go

      - name: Set up QEMU #setup do docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: igorsantana76/fullcycle-ci